### ISSUE TITLE
higher learning (GM SPAWN FIXABLE)

### ISSUE THREAD

**Issue by EhsanVreeken** [Arctic-WoW/Wrath#109]
http://wotlk.openwow.com/achievement=1956  the achievment higher learning which has your read the 8 books of arcane wizardry in dalaran is incorrectly scripted/spawned normall the books each spawn in a set location however, to make them rare blizzard has them cycle between irrelevant books aka dummy books, now when someone cracks one open they despawn in 3mins and an hour later from DESPAWN another book appears either another dummy book or a the correct book for that location needed for the acheivment, this locks out a pet as well 4 book need spawned until the random spawn can be scripted as the dummy books and the legit books do not despawn the books needed spawned are as follows: introduction, transmutation, enchantment and illusion

**Comment by Arctic-WoW** [comment]
Need more Info.

**Comment by EhsanVreeken** [comment]
every detail on how the achievment works and books spawn is listed, no further info could be needed or is possible
