### ISSUE TITLE
WOTLK not being able to be downloaded

### ISSUE THREAD

**Issue by shonale** [Arctic-WoW/Wrath#130]
currently happening now 7/17/2015
i signed up, and clicked the download for it using a utorrent and it tells me "world of warcraft 3.3.5a(no install)"

**Comment by Arctic-WoW** [comment]
It works just fine. It sounds like it is a Firewall blocking it.

**Comment by shonale** [comment]
![11756526_10206149325324228_44606291_n](https://cloud.githubusercontent.com/assets/13389819/8760375/31c079fe-2ccd-11e5-874e-10b8fa300749.jpg)

**Comment by shonale** [comment]
this is what it tells me, and i dont see a firewall pop-up
