### ISSUE TITLE
A Race Against Time

### ISSUE THREAD

**Issue by Tamirlang** [Arctic-WoW/Wrath#28]
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:11671:71\124h[A Race Against Time]\124h\124r");
Can target but not attack the mob, furthermore when you use the bomb it doesn't actually do anything. You throw it and it explodes but has no effect on the quest at all.

**Comment by Arctic-WoW** [comment]
Confirmed.  Quest is set to Auto Complete.
