### ISSUE TITLE
The Grand Melee quest

### ISSUE THREAD

**Issue by Garitra** [Arctic-WoW/Wrath#45]
http://wotlk.openwow.com/quest=13745
when i try to challenge the valiants nothing happens when i click the option i tried on all of them. also the ironforge valiant name is in red and cant talk to him. i tried doing this on the northern part of the ground with the champions and the same thing happend clicking to challenge them isnt working.

**Comment by Arctic-WoW** [comment]
Confirmed.  Quest is set to Auto Complete.
