### ISSUE TITLE
Engineering a Disaster

### ISSUE THREAD

**Issue by Tamirlang** [Arctic-WoW/Wrath#63]
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:12688:76\124h[Engineering a Disaster]\124h\124r");
Talk to NPC and after you hit the accept button the quest is not accepted and you can keep trying to speak with the NPC to accept it but it does not initiate.

**Comment by Arctic-WoW** [comment]
Quest is NOT Broken.  Works just fine.
