### ISSUE TITLE
Reclusive Runemaster

### ISSUE THREAD

**Issue by Tamirlang** [Arctic-WoW/Wrath#69]
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffffff00\124Hquest:12150:74\124h[Reclusive Runemaster]\124h\124r");
Fight the elite who gives the position for the mob in the next part of the chain but it does not register as complete.

**Comment by Arctic-WoW** [comment]
Confirmed.  Quest is set to Auto Complete.
