### ISSUE TITLE
Kickin' Nass and Takin' Manes 

### ISSUE THREAD

**Issue by valcastle** [Arctic-WoW/Wrath#80]
Nass does not spawn for me (Drenei Shaman) Has spawned for Jay

http://www.wowhead.com/quest=12630/kickin-nass-and-takin-manes

**Comment by EhsanVreeken** [comment]
Confirmed also spawns for gnome warlocks/ note had to drop quest repick up and ask to resummon him from npc however

**Comment by Arctic-WoW** [comment]
Confirmed.  Quest is set to Auto Complete.
