### ISSUE TITLE
WARLOCK QUEST Tome of the Cabal

### ISSUE THREAD

**Issue by EhsanVreeken** [Arctic-WoW/Wrath#97]
http://wotlk.openwow.com/quest=1802 item not spawned in wetlands, needed for warlock spell summon fel hunter

**Comment by Arctic-WoW** [comment]
Quest is NOT Bugged.

Tome of the Cabal X:-1152.770020 Y:177.587997 Z:0.451798 MapId:0
Damaged Chest X:-4925.589844 Y:-2344.580078 Z:-49.102100 MapId:1
